### ISSUE TITLE
Add unit tests across project

### ISSUE THREAD

**Issue by Shivam010** [Shivam010/bypass-cors#2]
Need to add unit tests for the handler in `main.go` and the helper functions in `helper.go`, so is to avoid any future bug.

**Comment by ahmedsharif865** [comment]
Is someone still working on this issue?

**Comment by Shivam010** [comment]
No, would you like to contribute?

**Comment by jmhobbs** [comment]
@Shivam010 Hello!  I added some tests for helper methods in #9.  Would you like a config file set up for a CI tool?  I personally like Travis but have experience configuring CircleCI too.

**Comment by Shivam010** [comment]
Hi @jmhobbs, thank you for your contribution. It would be better for me if you would add your contribution in #6 and create a PR for `dev` branch. I have some tests written in it. 

Follow the PR #6 and checkbox https://github.com/Shivam010/bypass-cors/pull/6#issue-315229803

**Comment by Shivam010** [comment]
Also, regarding the CI config, it's already set in with `GitHub Actions` https://github.com/Shivam010/bypass-cors/actions

**Comment by Shivam010** [comment]
Unit tests for pre-flight requests are only left to check. 
Closing this issue and creating a new one for `pre-flight` request
Thank you 

PS: New Issue #15
