### ISSUE TITLE
Add more example in README.md 

### ISSUE THREAD

**Issue by Shivam010** [Shivam010/bypass-cors#3]
Need some more examples with other `http.Methods` like `POST, PUT, DELETE`. 

If possible a _GIF_ of `fetch()` method first with CORS and then using the proxy server `https://non-cors.herokuapp.com/`

**Comment by NickCwh** [comment]
Hi @Shivam010 

For https://joke-api-strict-cors.appspot.com is there currently a POST/PUT/DELETE method?
Some suggestions:
(POST)
https://joke-api-strict-cors.appspot.com/jokes/add 
(PUT)
https://joke-api-strict-cors.appspot.com/jokes/add/id
(DELETE)
https://joke-api-strict-cors.appspot.com/jokes/id/delete

Or would you prefer me to just add the url examples based on another url with the necessary http methods?

**Comment by Shivam010** [comment]
> ....Or would you prefer me to just add the url examples based on another url with the necessary http methods?

Yes, the idea is just to provide the user with an equivalent practical example, where a normal request leads to `CORs error` and not with `bypass-cors`

**Comment by Shub3am** [comment]
anyone working on this?

**Comment by nishitiwari22** [comment]
Is this issue still open? I am looking to contribute to it.

**Comment by Shivam010** [comment]
Thanks for showing interest, @nishitiwari22!
Though, I have stopped the hosted service of the server, so I don't think how useful this issue would be, now! So, I am closing this one.
But if you want to learn something, new, you can try and explore it.
