### ISSUE TITLE
Add a landing page for the server

### ISSUE THREAD

**Issue by Shivam010** [Shivam010/bypass-cors#4]
A landing page is required, as of now the server only works as an API.
The root path, `/` requests should route to the landing page and rest all request should be routed to use the current handler of the API.

Currently, `https://non-cors.herokuapp.com/` returns `StatusPreconditionFailed` error
```json
{
  "error": {
    "Code": 412,
    "Message": "URL not provided",
    "Detail": {
      "method": "GET",
      "requestedURL": "/"
    }
  }
}
```
but instead should be route to a landing page describing the `bypass-cors` server.

**Suggestion**: `README.md` file can be utilized to create the landing page.

**Comment by 0xsubi** [comment]
@Shivam010 I have kept it as small as possible.
https://github.com/Shivam010/bypass-cors/pull/8

**Comment by Shivam010** [comment]
@sudhabindu1 Check the requested changes in the PR review.

**Comment by vakhariaheet** [comment]
@Shivam010 Can I try it?

**Comment by Shivam010** [comment]
@heet-vakharia 
Sure, you are most welcome.

Quick note: Try to utilize the `README.md` file

**Comment by vakhariaheet** [comment]
ok, Thank you

**Comment by Shub3am** [comment]
is anyone working on this?
