### ISSUE TITLE
Other information like Headers, Form values, context, etc needs to be passed downstream

### ISSUE THREAD

**Issue by hsaito** [Shivam010/bypass-cors#5]
I've found limited usability without being able to pass the headers (e.g. for auth token, etc.) -- perhaps with something like the following, but perhaps something bit more robust...

```
for k, v := range r.Header {
   req.Header.Add(k, v[0])
}
```

**Comment by Shivam010** [comment]
You are right, nice identification. It appears that I missed all the vital request's information, including `Headers`, `Form Values`, `Context`, etc
Currently, only request `Body` and `Method` is in use.

We should change the issue title to consider all the fields.

**Comment by Shivam010** [comment]
@hsaito 
Are you interested in taking the issue?

**Comment by hsaito** [comment]
@Shivam010 I would be happy to. Just I'm relatively new to Go language, but as I've done some experiment with this, I should be able to get to this with some ramp ups!

**Comment by Shivam010** [comment]
I'm sure you can.
I think that all we have to do is to copy the information from `r` to `req`.
All the best.
